
/*

var _str = ""

_str = "//THIS IS AN AUTOGENERATED SCRIPT, IT MAY ALSO CHANGE AT ANY TIME\n\nvar a;\n\n"

var i, o, j, _table, _list, _list_name;

_list = obj_data.hurtbox_list
_list_name = "hurtbox_list"
repeat(2) { //hurtboxes, then hitboxes
	for (j = array_length_1d(_list) - 1; j >= 0; j--) { //each character
		//loop through the 2d inner array and add it to the file
		_str += "a = [];\n"
		_table = _list[j]
		for (i = array_height_2d(_table) - 1; i >= 0; i--) {
			for (o = array_length_2d(_table, i) - 1; o >= 0; o--) {
				_str += "a[" + string(i) + "," + string(o) + "] = " + string(_table[i, o]) + ";\n"
			}
			show_debug_message("Currently doing i dimension: " + string(i))
		}
		_str += "global." + string(_list_name) + "[" + string(j) + "] = a\n"
		show_debug_message("Currently doing character: " + string(j))
	}
	_list = obj_data.hitbox_list //change which list
	_list_name = "hitbox_list"
}

show_debug_message("Writing to File")
var _file = file_text_open_write("Local Hitbox Copy.txt")
file_text_write_string(_file, _str)
file_text_close(_file)

//var _file = file_text_open_write(global.output_file)
//file_text_write_string(_file, _str)
//file_text_close(_file)




/*
old system
global.hitbox
[32000 sprites, 319 frames + 9 hitboxes + 11 entries]
[sprite_index, image_index*100 + index*11 + entry]

new system
global.hitbox_list[hitbox and hurtbox arrays]
global.hitbox_bal
[3200 sprites + 10 hitboxes, 1280 frames + 25 entries]

new new system

global.hitbox[sprite][frame][hitbox][data]

est ::  
var a = global.hitbox[spr_bal_forward_aerial] //sprite
a = a[2] //frame
a = a[0] //hitbox
a[9] = 2 //data


code test ::

var hitbox1 = [2, 4, 5, 6, 654, 654,6 45,6 546, 456,45 6,45 6,54 6,456 45,6 54,6 54,4]
var frame1 = [hitbox1, hitbox2, hitbox3, hitbox4 ....]
var sprite1 = [frame1, frame2, frame3, frame4, frame5, ....]


*/
var _buff = buffer_create(104857600, buffer_grow, 1)


buffer_write(_buff, buffer_text, "//THIS IS AN AUTOGENERATED SCRIPT, IT MAY ALSO CHANGE AT ANY TIME\n\n")

var i, o, j, k, l, _table, _list, _list_name;

_list = obj_data.hurtbox_list
_list_name = "hurtbox_list"
repeat(2) { //hurtboxes, then hitboxes
	buffer_write(_buff, buffer_text, "global." + _list_name + " = [\n")
	for (j = 0; j < array_length_1d(_list); j++) { //each character
		_table = _list[j] //get the array
		for (i = 0; i < array_height_2d(_table)/10 - 1; i++) { //for each sprite
			buffer_write(_buff, buffer_text, "\t[ //" + string(obj_data.sprite_array[i + _table[0, 0], NAME]) + " \n")
			for (o = 0; o < array_length_2d(_table, i)/25; o++) { //for each frame
				//check for break
				if (_table[i*10, o*25] = -10) { //if the first data point of the first hitbox is null
					//end this loop
					break;
				}
				buffer_write(_buff, buffer_text, "\t\t[ //frame " + string(o) + "\n")
				for (k = 0; k < 10; k++) { //for each hitbox
					//check for break
					if (_table[i*10 + k, o*25] = -10) { //if the first data point of the hitbox is null
						//end this loop
						break;
					}
					buffer_write(_buff, buffer_text, "\t\t\t[")
					for (l = 0; l < 25; l++) { //for each data point
						buffer_write(_buff, buffer_text, string(_table[i*10 + k, o*25 + l]) + ",")
					}
					//replace last , with ], newline
					buffer_seek(_buff, buffer_seek_relative, -1)
					buffer_write(_buff, buffer_text, "],\n")
				}
				//replace last ], newline with ] newline
				buffer_seek(_buff, buffer_seek_relative, -2)
				buffer_write(_buff, buffer_text, "\n\t\t],\n")
			}
			//replace last ], newline with ] newline
			buffer_seek(_buff, buffer_seek_relative, -2)
			buffer_write(_buff, buffer_text, "\n")
			//write the end of the sprite
			buffer_write(_buff, buffer_text, "\t],\n") 
		}
		
	}
	//replace last ], newline with ] newline for end of sprites
	buffer_seek(_buff, buffer_seek_relative, -2)
	buffer_write(_buff, buffer_text, "\n]\n\n")
	_list = obj_data.hitbox_list //change which list
	_list_name = "hitbox_list"
}

buffer_write(_buff, buffer_string, "") //write null terminator

show_debug_message(buffer_tell(_buff)) //output size of buffer

buffer_save_async(_buff, "Output_Buffer.buff", 0, buffer_tell(_buff)); //save to local backup
buffer_save_async(_buff, global.output_file, 0, buffer_tell(_buff)); //save to final desitination


/* FORMAT
[ //sprite
	[ //frame
		[1, 2, 3, 4, 5 ...data....],
		[1, 2, 3, 4, 5 ...data....],
		[1, 2, 3, 4, 5 ...data....],
		[1, 2, 3, 4, 5 ...data....]
	],
	[ //frame
		[1, 2, 3, 4, 5 ...data....],
		[1, 2, 3, 4, 5 ...data....],
		[1, 2, 3, 4, 5 ...data....],
		[1, 2, 3, 4, 5 ...data....]
	],
	[ //frame
		[1, 2, 3, 4, 5 ...data....],
		[1, 2, 3, 4, 5 ...data....],
		[1, 2, 3, 4, 5 ...data....],
		[1, 2, 3, 4, 5 ...data....]
	]
]